### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Just-Devi** [GenoX-Fome/funkin-utau#16]
Why is there no Selever voicebanks? Can you please add him, i really need it for a mod

**Comment by githubisveryepic** [comment]
Be patient.

**Comment by ACardboardBox1** [comment]
you can also just do it yourself, just grab a note from casanova and make a folder called "Selever FNF Voicebank". export the note as it's own little file and name it "a" or whatever. make sure it's the same file type as the other voicebanks as a extra measure to make sure it works. open the sample (or drag the folder into utau) and voila!

**Comment by GenoX-Fome** [comment]
They are on Blantados Github repository, check the readme

**Comment by Just-Devi** [comment]
> you can also just do it yourself, just grab a note from casanova and make a folder called "Selever FNF Voicebank". export the note as it's own little file and name it "a" or whatever. make sure it's the same file type as the other voicebanks as a extra measure to make sure it works. open the sample (or drag the folder into utau) and voila!

Oh, thank you!

**Comment by Just-Devi** [comment]
> They are on Blantados Github repository, check the readme

Where exactly? I've searched for it everywhere and tried searching for it with the search feature and i can't find it
