### ISSUE TITLE
Monster voicebank

### ISSUE THREAD

**Issue by AngelPiggyYT** [GenoX-Fome/funkin-utau#18]
I want the monster voicebank to be available😭

**Comment by TheTristanShow** [comment]
Idk if i'll come out

**Comment by ACardboardBox1** [comment]
plus it isnt genox's voicebank so.....

**Comment by AngelPiggyYT** [comment]
alright

**Comment by GenoX-Fome** [comment]
The person who made that voicebank decided to leave FNF, along with their voicebanks. for respect to them i will not add it back
