### ISSUE TITLE
Voicebanks Not Working

### ISSUE THREAD

**Issue by Domino054** [GenoX-Fome/funkin-utau#19]
Hey there. I noticed that some of the FNF voicebanks don't seem to be working properly. You think you could fix this problem for me?

**Comment by ACardboardBox1** [comment]
What do you mean? can you describe the issue in detail so i can help?

**Comment by Domino054** [comment]
Well, some of the voicebanks’ wav files could stand to be updated, as some of them make a weird buzzing sound on certain notes.

**Comment by ACardboardBox1** [comment]
> 
> 
> Well, some of the voicebanks’ wav files could stand to be updated, as some of them make a weird buzzing sound on certain notes.

can you name some examples so i can try and fix them

**Comment by Domino054** [comment]
There's Skid and Pump for an example.

**Comment by GenoX-Fome** [comment]
Some of them dont sounds for many reasons. One needs to use other resamplers (which you can find online, fresamp and moresampler are good options), other needs specific range of notes, and other wasnt just made for UTAU (like Pico). the last one its because the frq files
