### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by AngelPiggyYT** [GenoX-Fome/funkin-utau#22]
can you make "starecrown" "anders" "cesar" "selever" "imposter"

**Comment by AngelPiggyYT** [comment]
I REALLY NEED THESE FOR MY MOOOODS

**Comment by GenoX-Fome** [comment]
check blantados github for these

**Comment by githubisveryepic** [comment]
selever, starecrown, anders and cesar aren't available on blantados github
