### ISSUE TITLE
where is cassandra's voicebank?

### ISSUE THREAD

**Issue by antoineelcrak** [GenoX-Fome/funkin-utau#26]

**Comment by PaRappa1996** [comment]
It's on google drive: https://drive.google.com/drive/folders/12fHT2a_dXBAdO98CzC7_NfD2PmvQxX9M (credit to ramen noodiles)

**Comment by GenoX-Fome** [comment]
Uh, the original creator of Cassandra asked me to delete the voicebank from there, but you can download it from their YT Community Tab
