### ISSUE TITLE
Where is the miku voice bank 

### ISSUE THREAD

**Issue by DierdixYT** [GenoX-Fome/funkin-utau#29]
I looked for it everywhere.
Plz help me

**Comment by GenoX-Fome** [comment]
Miku can't be on UTAU because it's against her original software TOS.
You could either use the actual chromatic or get VOCALOID (where her voice comes from)

**Comment by BonnyeBonbox** [comment]
Hey genox,can i use ur the week 1-7 voices for my mod? I cant make voices like your voices,my mod is named Bonnye And Friends(only week 1,2,3 and 7 are ready)
The mod is the mod is available on Android as an APK

**Comment by BonnyeBonbox** [comment]
Hey genox,can i use ur the week 1-7 voices for my mod? I cant make voices like your voices,my mod is named Bonnye And Friends(only week 1,2,3 and 7 are ready)
The mod is the mod is available on Android as an APK
