### ISSUE TITLE
i don't know how to download it

### ISSUE THREAD

**Issue by soravo** [GenoX-Fome/funkin-utau#3]
hi, my issue is that i do  not know how to download this. i know that download is possible, i do not know how to do it myself. btw i am on android

**Comment by GenoX-Fome** [comment]
Download from Source Code, also UTAU don't works on Android.

**Comment by HatsuneMiku-github** [comment]
> Download from Source Code, also UTAU don't works on Android.

As I remember They might be using exagear to use utau on android 

Exagear: An app to use/play PC games/apps on android (you can't use/play any apps/games higher than 32 bit)

Or they might be using PaintVoice
PaintVoice: Limited Utau on android 
By limited I mean that alot of stuff are missing in it Making Voicebanks, Using unlimited Japanese words, making UTAUs speak in other languages etc are missing
