### ISSUE TITLE
There needs to be a 2 new boyfriend sounds and 2 new spookeez skid sounds.

### ISSUE THREAD

**Issue by githubisveryepic** [GenoX-Fome/funkin-utau#6]
1. Haha
2. Yeah
Those are the sounds that need to be added.

**Comment by ACardboardBox1** [comment]
imo they arent needed 
plus you can just get the fnf song stems and add them. (they are open source, a quick google search might find em.)

**Comment by githubisveryepic** [comment]
i dont know how to create frq files
but yeah i think "need" was an over exaggeration lol (i didn't spell it right i think)

**Comment by GenoX-Fome** [comment]
UTAU would probably make these too flat, so it would lose their original tune/emotions lol
also when u have a folder with only .wavs, UTAU automatically generates frq for them (try resampler.dll)
