### ISSUE TITLE
Not workin

### ISSUE THREAD

**Issue by Foxy2021pidorasiaktovsyaletoima** [GenoX-Fome/funkin-utau#7]
Hello i tried to make song but not hearing anything i tried also open Wiki (at github right here ) but it doesnt let me

**Comment by GenoX-Fome** [comment]
-The UST/song needs to be on Romaji CV (lyrics like "a" "e" "i" "o" or "u" needs to be on the notes)
-Select all the UST with right click > Select All, then press play
-You maybe didn't select the voicebank and you're using the default UTAU one
-try changing to resampler.dll on the Project Settings

**Comment by GenoX-Fome** [comment]
Check the Wiki, which is already added
